twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # To easily loop supported locales and show alternative links (I18N links for an Twig extension)
        app_locales: '%app_locales%'
    strict_variables: '%kernel.debug%'
